services:
  redis:
    image: redis:latest
    container_name: redis-aula
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:   

# PARA CRIAR O COMPOSE PODEMOS BUSCAR EM DOCKERHUB
# Subir o container docker compose up -d